# Admin Configuration - File ẩn chứa thông tin admin
# File này không nên được commit vào git repository

admin:
  credentials:
    email: admin@webtuthien.com
    password: admin123
    # Mật khẩu nên được hash trong production
    # password_hash: $2a$10$N9qo8uLOickgx2ZMRZoMye...
  
  security:
    session_timeout: 24h
    max_login_attempts: 5
    lockout_duration: 30m
    
  features:
    enable_dashboard: true
    enable_user_management: true
    enable_campaign_management: true
    enable_donation_management: true
